name: onet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit-dev=11.1.1
  - cudatoolkit=11.1.74
  - cython
  - imageio
  - numpy
  - matplotlib
  - pandas
  - pillow
  - pyembree
  - pytest
  - python=3.8
  - pytorch=1.9.1
  - pyyaml=3.13
  - scikit-image
  - scipy
  - tensorboard=2.6.0
  - tensorboardx
  - torchvision=0.10.1
  - tqdm
  - trimesh
  - pip:
    - h5py
    - plyfile

