name: onet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pytorch3d
  - defaults
dependencies:
  - cudatoolkit-dev=11.1.1
  - cudatoolkit=11.1.74
  - cython
  - imageio
  - numpy
  - matplotlib
  - pandas
  - pillow
  - pyembree
  - pytest
  - python=3.8
  - pytorch=1.9.1
  - pyyaml
  - scikit-image
  - scipy
  - tensorboard=2.6.0
  - tensorboardx
  - torchvision=0.10.1
  - tqdm
  - trimesh
  - pip=21.3.1
  - setuptools=59.5.0
  - easydict=1.9
  - pytorch-lightning=1.4.9
  - pytorch3d=0.6.1
  - pip:
    - h5py
    - plyfile
    - git+https://github.com/bayesiains/nflows.git
    - umnn

